services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: mylibrary_back
    ports:
      - "3000:3000"
    volumes:
      - ./back/src:/app/src
    env_file:
      - ./back/.env
    depends_on:
      - db

  front:
    build: ./front
    container_name: mylibrary_front
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./front/src:/app/src
    env_file:
      - ./front/.env
    depends_on:
      - back

  db:
    image: mysql:8.4
    container_name: mylibrary_db
    volumes:
      - ./db/data:/var/lib/mysql
    env_file:
      - ./db/.env
